FROM maven:3.5-jdk-8-alpine as build

COPY mailService /src/mail

WORKDIR /src

RUN cd mail && mvn clean package


FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=build /src/mail/target/mailService-0.0.1-SNAPSHOT.jar /app
CMD java -jar mailService-0.0.1-SNAPSHOT.jar
