apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "gamesinfodb" 
  labels:
    app: "gamesinfodb" 
    release: "gamesinfodb-0.1.0" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "gamesinfodb" 
      release: "gamesinfodb-0.1.0" 
  template:
    metadata:
      labels:
        app: "gamesinfodb" 
        release: "gamesinfodb-0.1.0" 
    spec:
      containers:
        - name: "gamesinfodb"
          image: "{{ .Values.mysql_image.repository }}:{{ .Values.mysql_image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "gugus"