apiVersion: v1
kind: Service
metadata:
  name: "gamesinfodb"
  labels:
    app: "gamesinfodb" 
    release: "gamesinfodb-0.1.0" 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysqlport
  selector:
    app: "gamesinfodb" 
    release: "gamesinfodb-0.1.0" 
