apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "GamesInfo.fullname" . }}
  labels:
    app: {{ include "GamesInfo.name" . }}
    chart: {{ include "GamesInfo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "GamesInfo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "GamesInfo.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-gamesinfodb
          image: busybox
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 gamesinfodb 3306 && exit 0 || sleep 3; done; exit 1"]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8543
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
